### PR TITLE
Add api domain for ease of use

### LINKED ISSUE #4: (Easy) Allow the user to give just the API URL in `init` function call
The `init` function call can be seen here: https://supertokens.io/docs/ios/init:
```
try SuperTokens.initialise(refreshTokenEndpoint: "https://api.example.com/session/refresh", sessionExpiryStatusCode: 401, refreshAPICustomHeaders: NSDictionary())
```

As seen above, the `refreshTokenEndpoint` must be a full path to their refresh API endpoint. Instead, we need to change it so that if they give:
- `https://api.example.com` or `https://api.example.com/`, it treats it as `https://api.example.com/session/refresh`
- `https://api.example.com/some/other/path`, it treats it as `https://api.example.com/some/other/path`

Essentially, we want them to just give them API domain for ease of use.

### PR DESCRIPTION
**Pull request by nugmanoff**
Closes #4

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
Thanks! It would be great to have a few tests written for this change.

**Comment by nugmanoff** [comment]
@rishabhpoddar I am not quite getting the point of transformations that are done to the api endpoint string in `getApiDomain` function, it seems to just trim everything up until to the second component in the path

e.g. `refreshTokenEndpoint = https://api.example.com/session/refresh` and `getApiDomain` function will return `https://api.example.com/session`

I'd be grateful if you'd provide more context here, because to me `getApiDomain` seems strange for now.

I can rewrite it if you give the context of what is considered to be "valid url provided for refresh token", then I will rewrite the function using URL and URLComponent classes and just test it easily.

**Comment by rishabhpoddar** [comment]
Actually, `getApiDomain` is not required anymore. The `apiDomain` static variable was supposed to be used for filtering out interceptor usage. But since we are not using Interceptors at all, there is no need to have that variable, hence, that function is not needed anymore.

So you can remove:
- `getApiDomain` function
- `static var apiDomain: String? = nil`
- `SuperTokens.apiDomain = try SuperTokens.getApiDomain(refreshTokenEndpoint: refreshTokenEndpoint)`

-----------
I have also added a new issue about changing this implementation to use interceptors with `URLSession`, so that it's easier for users to use this lib. Though, I'm not sure if that's possible at all.

**Comment by nugmanoff** [comment]
@rishabhpoddar got it, thanks!

But one more question, where does the code that I've written goes now if `getApiDomain` functions gets removed?

What will be the point of the PR - is just deleting the parts you mentioned would be enough?

**Comment by rishabhpoddar** [comment]
> What will be the point of the PR - is just deleting the parts you mentioned would be enough?

No. So the input `refreshTokenEndpoint` to the [`initialise` function](https://github.com/supertokens/supertokens-ios/blob/c4f1e86b13399c1dcbe11971728d4ecfebcb8668/SuperTokensSession/Classes/SuperTokens.swift#L26) needs to be transformed according to the logic you have written before being assigned in [this](https://github.com/supertokens/supertokens-ios/blob/c4f1e86b13399c1dcbe11971728d4ecfebcb8668/SuperTokensSession/Classes/SuperTokens.swift#L31) line.

For example, is the `refreshTokenEndpoint` is `https://api.example.com`, then the value assigned to `SuperTokens.refreshTokenEndpoint` should be `https://api.example.com/session/refresh`

The above, plus the deletion of `getApiDomain` function along with the two other code snippets mentioned in the previous comment.

------------------
Apologies for the confusion for this PR, and thank you for helping out :)

**Comment by nugmanoff** [comment]
@rishabhpoddar thanks for helping out! Can you please take a look at the updated version? I've added some tests as well

**Comment by rishabhpoddar** [comment]
Hi,
A few points:
- In the test, `testSessionApiBaseResolvedCorrectlyAgainstSomeOtherPathUrl` does not actually call the `initialise` function with another path URL. Maybe you want to init it with `"https://api.example.com/some/other/url"` and check that that's what us set?
- You may want to remove `SuperTokens.refreshTokenEndpoint = refreshTokenEndpoint` since it's redundant now.


Apart from the above, it looks good!

**Comment by nugmanoff** [comment]
@rishabhpoddar oh, sorry for such silly mistakes ;( I've update the PR with the final revision

**Comment by rishabhpoddar** [comment]
Thanks @nugmanoff :))

**Pull request merged**
